// Command generate_unicode15 writes the dependency-free Unicode 15 tables used
// by the matcher. It must be run with the pinned Go 1.26.0 toolchain.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"
)

func main() {
	out := flag.String("out", "lib/dockerignore/unicode15.ex", "generated Elixir output")
	flag.Parse()

	if unicode.Version != "15.0.0" {
		panic(fmt.Sprintf("expected Unicode 15.0.0, got %s", unicode.Version))
	}

	// regexp/syntax canonicalizes the requested name first, then looks it up in
	// unicode.Categories and unicode.Scripts without canonicalizing their keys.
	// Keep only direct keys that remain reachable through that exact sequence.
	tables := map[string]*unicode.RangeTable{}
	names := map[string]bool{"Any": true, "Assigned": true, "ASCII": true}
	for name, table := range unicode.Categories {
		if name == canonicalName(name) {
			tables[name] = table
			names[name] = true
		}
	}
	// regexp/syntax handles LC as the one non-canonical category key.
	tables["Lc"] = unicode.Categories["LC"]
	names["LC"] = true

	for name, table := range unicode.Scripts {
		if name == canonicalName(name) {
			tables[name] = table
			names[name] = true
		}
	}

	aliases := map[string]string{}
	for alias, actual := range unicode.CategoryAliases {
		aliases[canonicalName(alias)] = canonicalName(actual)
		names[alias] = true
	}

	file, err := os.Create(*out)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	w := bufio.NewWriter(file)
	defer w.Flush()

	fmt.Fprintln(w, "# Generated by scripts/oracle/generate_unicode15 with Go 1.26.0 (Unicode 15.0.0).")
	fmt.Fprintln(w, "# Source: Go standard library unicode.Categories, CategoryAliases, and Scripts.")
	fmt.Fprintln(w, "# Lookup names mirror Go regexp/syntax canonicalName followed by its direct map lookup.")
	fmt.Fprintln(w, "# DO NOT EDIT.")
	fmt.Fprintln(w, "defmodule Dockerignore.Unicode15 do")
	fmt.Fprintln(w, "  @moduledoc false")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  @unicode_version \"15.0.0\"")
	fmt.Fprintln(w, "  @go_version \"1.26.0\"")
	fmt.Fprintln(w, "  @any {{0x0, 0x10FFFF, 1}}")
	fmt.Fprintln(w, "  @ascii {{0x0, 0x7F, 1}}")
	fmt.Fprint(w, "  @cn ")
	writeTable(w, unicode.Cn)
	fmt.Fprintln(w)
	fmt.Fprint(w, "  @white_space ")
	writeTable(w, unicode.Properties["White_Space"])
	fmt.Fprintln(w)

	tableNames := sortedKeys(tables)
	fmt.Fprintln(w, "  @tables %{")
	for i, name := range tableNames {
		fmt.Fprintf(w, "    %q => ", name)
		writeTable(w, tables[name])
		if i+1 < len(tableNames) {
			fmt.Fprint(w, ",")
		}
		fmt.Fprintln(w)
	}
	fmt.Fprintln(w, "  }")

	aliasNames := sortedKeys(aliases)
	fmt.Fprintln(w, "  @aliases %{")
	for i, name := range aliasNames {
		fmt.Fprintf(w, "    %q => %q", name, aliases[name])
		if i+1 < len(aliasNames) {
			fmt.Fprint(w, ",")
		}
		fmt.Fprintln(w)
	}
	fmt.Fprintln(w, "  }")

	classNames := sortedKeys(names)
	fmt.Fprintln(w, "  @class_names [")
	for i, name := range classNames {
		fmt.Fprintf(w, "    %q", name)
		if i+1 < len(classNames) {
			fmt.Fprint(w, ",")
		}
		fmt.Fprintln(w)
	}
	fmt.Fprintln(w, "  ]")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  @doc false")
	fmt.Fprintln(w, "  def provenance, do: %{go: @go_version, unicode: @unicode_version}")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  @doc false")
	fmt.Fprintln(w, "  def class_names, do: @class_names")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  @doc false")
	fmt.Fprintln(w, "  def lookup(name) when is_binary(name) do")
	fmt.Fprintln(w, "    case canonical_name(name) do")
	fmt.Fprintln(w, "      \"Any\" -> {:ok, @any, false}")
	fmt.Fprintln(w, "      \"Assigned\" -> {:ok, @cn, true}")
	fmt.Fprintln(w, "      \"Ascii\" -> {:ok, @ascii, false}")
	fmt.Fprintln(w, "      canonical ->")
	fmt.Fprintln(w, "        canonical = Map.get(@aliases, canonical, canonical)")
	fmt.Fprintln(w, "        case Map.fetch(@tables, canonical) do")
	fmt.Fprintln(w, "          {:ok, ranges} -> {:ok, ranges, false}")
	fmt.Fprintln(w, "          :error -> :error")
	fmt.Fprintln(w, "        end")
	fmt.Fprintln(w, "    end")
	fmt.Fprintln(w, "  end")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  @doc false")
	fmt.Fprintln(w, "  def space?(codepoint) when is_integer(codepoint), do: member?(@white_space, codepoint)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  @doc false")
	fmt.Fprintln(w, "  def member?(ranges, codepoint) when is_tuple(ranges) and is_integer(codepoint) do")
	fmt.Fprintln(w, "    if codepoint in 0..0x10FFFF, do: member?(ranges, codepoint, 0, tuple_size(ranges) - 1), else: false")
	fmt.Fprintln(w, "  end")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  defp member?(_ranges, _codepoint, low, high) when low > high, do: false")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  defp member?(ranges, codepoint, low, high) do")
	fmt.Fprintln(w, "    middle = div(low + high, 2)")
	fmt.Fprintln(w, "    {first, last, stride} = elem(ranges, middle)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "    cond do")
	fmt.Fprintln(w, "      codepoint < first -> member?(ranges, codepoint, low, middle - 1)")
	fmt.Fprintln(w, "      codepoint > last -> member?(ranges, codepoint, middle + 1, high)")
	fmt.Fprintln(w, "      true -> rem(codepoint - first, stride) == 0")
	fmt.Fprintln(w, "    end")
	fmt.Fprintln(w, "  end")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  defp canonical_name(name) do")
	fmt.Fprintln(w, "    {bytes, _first?} =")
	fmt.Fprintln(w, "      for <<byte <- name>>, reduce: {[], true} do")
	fmt.Fprintln(w, "        {bytes, first?} when byte in [95, 45, 32] -> {bytes, first?}")
	fmt.Fprintln(w, "        {bytes, true} -> {[uppercase(byte) | bytes], false}")
	fmt.Fprintln(w, "        {bytes, false} -> {[lowercase(byte) | bytes], false}")
	fmt.Fprintln(w, "      end")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "    bytes |> Enum.reverse() |> :erlang.list_to_binary()")
	fmt.Fprintln(w, "  end")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  defp uppercase(byte) when byte in ?a..?z, do: byte - (?a - ?A)")
	fmt.Fprintln(w, "  defp uppercase(byte), do: byte")
	fmt.Fprintln(w, "  defp lowercase(byte) when byte in ?A..?Z, do: byte + (?a - ?A)")
	fmt.Fprintln(w, "  defp lowercase(byte), do: byte")
	fmt.Fprintln(w, "end")
}

func canonicalName(name string) string {
	var b strings.Builder
	first := true
	for i := 0; i < len(name); i++ {
		c := name[i]
		switch {
		case c == '_' || c == '-' || c == ' ':
			continue
		case first:
			if c >= 'a' && c <= 'z' {
				c -= 'a' - 'A'
			}
			first = false
		default:
			if c >= 'A' && c <= 'Z' {
				c += 'a' - 'A'
			}
		}
		b.WriteByte(c)
	}
	return b.String()
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func writeTable(w *bufio.Writer, table *unicode.RangeTable) {
	ranges := make([]string, 0, len(table.R16)+len(table.R32))
	for _, r := range table.R16 {
		ranges = append(ranges, fmt.Sprintf("{0x%X, 0x%X, %d}", r.Lo, r.Hi, r.Stride))
	}
	for _, r := range table.R32 {
		ranges = append(ranges, fmt.Sprintf("{0x%X, 0x%X, %d}", r.Lo, r.Hi, r.Stride))
	}
	fmt.Fprintf(w, "{%s}", strings.Join(ranges, ", "))
}
